---
name: chinapython
version: 1

handle:
- expire: if(path ~ "(.*)\.(js|css|jpg|png|gif|ico)") time 31536000
- compress: if(out_header["Content-Length"] >= 1240) compress

libraries:
- name: lxml
  version: "2.3.4"

cron:
- description: cron_test
  url: /load
  schedule: "*/24 * * * *"
...
